xargs rm <<"EOF"
       con_avr_cdc.c
       con_pico.c
       con_posix.c
       con_uboot.c
       con_uefi.c
       eeprom_image.c
       eeprom_pico.c
       eeprom_posix.c
       eeprom_uboot.c
       eeprom_uefi.c
       i8080.S
       io_pico.c
       io_base.c
       led_pico.c
       led_base.c
       platform_nacl.h
       platform_pico.c
       platform_posix.c
       platform_uboot.c
       platform_uefi.c
       platform_nacl.c
       sdcard_pico.c
       sdcard_picoflash.c
       sdcard_posix.c
       sdcard_softpico.c
       sdcard_uboot.c
       sdcard_uefi.c
       sram_avr.c
       sram_avr_asm.mac
       sram_avr_asm.S
       sram_base.c
       sram_pico.c
